version: 2

sources:
  - name: public
    tables:
      - name: ahs_factures
      - name: csm_factures

models:
  - name: t_customers
    description: "consolidated orders"
    config:
      schema: merged
      alias: fact_factures


